/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.barazkide.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.sareweb.barazkide.model.Following;
import net.sareweb.barazkide.model.FollowingModel;
import net.sareweb.barazkide.model.FollowingSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Following service. Represents a row in the &quot;Barazkide_Following&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.sareweb.barazkide.model.FollowingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FollowingImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see FollowingImpl
 * @see net.sareweb.barazkide.model.Following
 * @see net.sareweb.barazkide.model.FollowingModel
 * @generated
 */
@JSON(strict = true)
public class FollowingModelImpl extends BaseModelImpl<Following>
	implements FollowingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a following model instance should use the {@link net.sareweb.barazkide.model.Following} interface instead.
	 */
	public static final String TABLE_NAME = "Barazkide_Following";
	public static final Object[][] TABLE_COLUMNS = {
			{ "followingId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "gardenId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Barazkide_Following (followingId LONG not null primary key,userId LONG,gardenId LONG)";
	public static final String TABLE_SQL_DROP = "drop table Barazkide_Following";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.net.sareweb.barazkide.model.Following"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.net.sareweb.barazkide.model.Following"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Following toModel(FollowingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Following model = new FollowingImpl();

		model.setFollowingId(soapModel.getFollowingId());
		model.setUserId(soapModel.getUserId());
		model.setGardenId(soapModel.getGardenId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Following> toModels(FollowingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Following> models = new ArrayList<Following>(soapModels.length);

		for (FollowingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.net.sareweb.barazkide.model.Following"));

	public FollowingModelImpl() {
	}

	public long getPrimaryKey() {
		return _followingId;
	}

	public void setPrimaryKey(long primaryKey) {
		setFollowingId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_followingId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Following.class;
	}

	public String getModelClassName() {
		return Following.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("followingId", getFollowingId());
		attributes.put("userId", getUserId());
		attributes.put("gardenId", getGardenId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long followingId = (Long)attributes.get("followingId");

		if (followingId != null) {
			setFollowingId(followingId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long gardenId = (Long)attributes.get("gardenId");

		if (gardenId != null) {
			setGardenId(gardenId);
		}
	}

	@JSON
	public long getFollowingId() {
		return _followingId;
	}

	public void setFollowingId(long followingId) {
		_followingId = followingId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public long getGardenId() {
		return _gardenId;
	}

	public void setGardenId(long gardenId) {
		_gardenId = gardenId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Following.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Following toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Following)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		FollowingImpl followingImpl = new FollowingImpl();

		followingImpl.setFollowingId(getFollowingId());
		followingImpl.setUserId(getUserId());
		followingImpl.setGardenId(getGardenId());

		followingImpl.resetOriginalValues();

		return followingImpl;
	}

	public int compareTo(Following following) {
		long primaryKey = following.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Following following = null;

		try {
			following = (Following)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = following.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Following> toCacheModel() {
		FollowingCacheModel followingCacheModel = new FollowingCacheModel();

		followingCacheModel.followingId = getFollowingId();

		followingCacheModel.userId = getUserId();

		followingCacheModel.gardenId = getGardenId();

		return followingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{followingId=");
		sb.append(getFollowingId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", gardenId=");
		sb.append(getGardenId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("net.sareweb.barazkide.model.Following");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>followingId</column-name><column-value><![CDATA[");
		sb.append(getFollowingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gardenId</column-name><column-value><![CDATA[");
		sb.append(getGardenId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Following.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Following.class
		};
	private long _followingId;
	private long _userId;
	private String _userUuid;
	private long _gardenId;
	private Following _escapedModelProxy;
}